spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TaTa
    username: postgres
    password: "@Amin0076"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true


