spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TaTa
    username: postgres
    password: "@Amin0076"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true       # برای بهتر خواندن کوئری‌ها فعال کن
        show_sql: true        # نمایش کوئری SQL فعال است
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG            # نمایش کوئری‌های SQL
        type:
          descriptor:
            sql:
              BasicBinder: TRACE   # نمایش مقادیر پارامترهای bind شده
